-- MySQL Script generated by MySQL Workbench
-- Aug 08 2019
-- Infrastructure Team

CREATE DATABASE IF NOT EXISTS baltimore
CHARACTER SET utf8mb4
collate utf8mb4_0900_ai_ci;

USE baltimore;

CREATE TABLE IF NOT EXISTS baltimore.geocode (
geocode_id BIGINT NOT NULL AUTO_INCREMENT ,
coordinates POINT,
address VARCHAR (2000),
response_base64 TEXT,
PRIMARY KEY(geocode_id)
);

CREATE USER IF NOT EXISTS 'root'@'localhost' IDENTIFIED BY 'benutzenmaschine';

GRANT ALL ON baltimore.* TO 'bmore'@'localhost';
